language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get -qq update

before_script:
  - autoreconf -vfi

script: 
  - ./configure || (cat config.log; false)
  - make clean all check distcheck || (cat test/test-suite.log; false)

## whitelist
branches:
  only:
    - master

notifications:
  email:
    - devel@fresse.org
